## Numpy

NumPy is a fundamental library for scientific computing in Python. It Provides support for arrays and matrices, along with a collection of mathematical function to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
import numpy as np

## create array using numpy
## create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)
# print(type(arr2))
# arr2.shape

array([[1, 2, 3, 4, 5]])

In [6]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [8]:
## 2D array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
## identity matrix

np.eye(3
       )

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
## attribute of array
arr=np.array([[1,2,3],[4,5,6]])
print("Array",arr)
print("Shape",arr.shape)
print("Number of dimensions",arr.ndim)
print("Size (number of elements):",arr.size)
print("Data type:",arr.dtype)
print("Item size (In bytes)",arr.itemsize)

Array [[1 2 3]
 [4 5 6]]
Shape (2, 3)
Number of dimensions 2
Size (number of elements): 6
Data type: int64
Item size (In bytes) 8


In [18]:
## Numpy Vectorized Operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,203,494,45,45])

#addition
print("Addition",arr1+arr2)
print("Sub",arr1-arr2)
print("Multiplication",arr1 * arr2)
print("Division",arr1/arr2)

Addition [ 11 205 497  49  50]
Sub [  -9 -201 -491  -41  -40]
Multiplication [  10  406 1482  180  225]
Division [0.1        0.00985222 0.00607287 0.08888889 0.11111111]


In [19]:
## Universal function

arr = np.array([2,3,4,5,6])
print(np.sqrt(arr))

## exponential

print(np.exp(arr))

## Sine

print(np.sin(arr))

## natural log

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [21]:
## array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[8,3,3,6]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [8 3 3 6]]


In [23]:
arr[0][1]

np.int64(2)

In [24]:
arr[2:]

array([[8, 3, 3, 6]])

In [25]:
arr[1:,2:,]

array([[7, 8],
       [3, 6]])

In [26]:
## Modify the element

arr[0,0] = 100

In [27]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  8,   3,   3,   6]])

In [28]:
arr[1:]=99

In [29]:
arr

array([[100,   2,   3,   4],
       [ 99,  99,  99,  99],
       [ 99,  99,  99,  99]])

In [30]:
### Statical concept

## to have a mean of 0 and standard deviation

data = np.array([1,2,3,4,5])
mean = np.mean(data)
std_dev = np.std(data)


## Normalize the data

normalized_data = (data-mean)/std_dev
print("Normalized data: ",normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [31]:
## Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[data>5]

array([ 6,  7,  8,  9, 10])

In [32]:
data[(data>=5)& (data<=8)]

array([5, 6, 7, 8])